"""moved description to listings and out of records

Revision ID: 0254aa55a58d
Revises: 9eda90b7b7f7
Create Date: 2025-06-02 11:36:49.274666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0254aa55a58d'
down_revision = '9eda90b7b7f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
