"""Add relationships to Favorite

Revision ID: 48040d84680e
Revises: b81a279004fe
Create Date: 2025-05-28 16:57:02.800124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48040d84680e'
down_revision = 'b81a279004fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
